# yaml-language-server: $schema=config-schema.json
caching:
  intake_tolerance: 0.01
  flywheel_tolerance: 0.005
  hood_tolerance: 0.002
  drivetrain_tolerance: 0.02

turret:
  max_turn_power: 0.5
  min_turn_power: 0.12
  max_power_output: 0.5
  feed_forward: 0.08
  orientation:
    logo: "RIGHT"
    usb: "UP"
  turn:
    offset_const: 260
    limit_const: 160
  pidf:
    p: 0.01
    i: 0.0005
    d: 0.003
    f: 0
  tolerance:
    max_drift: 3
    near_cutoff: 1
    near_val: 45
    min_deg: 0.5
    max_deg: 2

vision:
  camera_position:
    x: -12
    y: 9
    z: 19.5
  camera_orientation:
    yaw: 0
    pitch: -90
    roll: 0

sentinel:
  robot_width: 18
  rotation_lookahead: 0.45
  goals:
    size: 6
    min_y: 69
    red_goal_x: 128.5
    red_goal_y: 135
    blue_goal_x: 15.5
    blue_goal_y: 135

casablanca:
  repulsion:
    power: 0.12
    decel_safety_factor: 0.7
  depth:
    slow_down: 8
    hard_stop: 10
  side:
    slow_down: 4
    hard_stop: 3
  lane_blend_distance: 12
  friction:
    x: 0.1
    y: 0.2
    rot: 0.12
  smoothing:
    time: 0.22
    back_lift_multiplier: 2.5
  heading_lock:
    enabled: true
    kp: 0.8
    max_power: 0.04
    deadband: 0.01

shooter:
  max_rpm: 1500
  auto_shoot_mode: true
  min_transfer_threshold: 0.93
  pidf:
    p: 150
    i: 0
    d: 0
    f: 22.8
  launch_params:
    threshold_distance: 33
    near:
      launch_power: 0.59
      wait_time: 2000
    far:
      blue_base_power: 0.58
      red_base_power: 0.6
      power_scale: 300
      wait_time_scale: 68

auto:
  drink_wait_ms: 1200
  shoot_wait_ms: 1300
  launch_power: 0.71
  transfer_power: 0.12
  min_transfer_threshold: 0.93
  opposite_drink_wait_ms: 1250
  opposite_shoot_wait_ms: 2450
  opposite_launch_power: 0.86
  opposite_transfer_power: 0.12
  opposite_min_transfer_threshold: 0.95

teleop:
  max_speed: 0.6
  poses:
    red:
      start: [87, 8, 90]
      score: [61, 21, 0]
      drink: [129, 60.5, 42]
      park: [37.5, 32, 270]
    blue:
      start: [57, 8, 90]
      score: [81, 21, 121]
      drink: [12, 60.5, 140]
      park: [105.5, 31, 270]

auto_poses:
  normal:
    blue:
      start: [27, 128, 135]
      score: [56, 80, 127]
      final_score: [57, 104, 144]
      drink_cp: [45, 72, 140]
      drink_end: [10.5, 61, 140]
      pickup1_cp: [41, 84, 180]
      pickup1_end: [18, 84, 180]
      pickup2_cp: [56, 55, 180]
      pickup2_end: [12, 59, 180]
      pickup3_cp: [56, 25, 180]
      pickup3_end: [11, 36, 180]
    red:
      start: [117, 128, 45]
      score: [88, 80, 50]
      mid_score: [88, 80, 47]
      drink_cp: [96, 72, 40]
      drink_end: [130, 60.5, 40]
      pickup1_cp: [100, 84, 0]
      pickup1_end: [123, 84, 0]
      pickup2_cp: [84, 55, 0]
      pickup2_end: [130, 60, 0]
      pickup3_cp: [88, 25, 0]
      pickup3_end: [130, 36, 0]
  opposite:
    blue:
      start: [57, 8, 90]
      score: [59, 20, 111]
      drink_cp: [50, 50, 140]
      drink_end: [13, 60.5, 140]
      pickup2_cp: [60, 68, 180]
      pickup2_end: [12, 58, 180]
      pickup3_cp: [60, 40, 180]
      pickup3_end: [12, 36, 180]
      pickup4_cp: [50, 20, 190]
      pickup4_end: [12, 10, 190]
      park: [40, 20, 111]
    red:
      start: m
      score: m
      drink_cp: m
      drink_end: m
      pickup2_cp: m
      pickup2_end: m
      pickup3_cp: m
      pickup3_end: m
      pickup4_cp: m
      pickup4_end: m
      park: m
