# yaml-language-server: $schema=generated/config-schema.json
turret:
  max_power_output: 0.5
  ks: 0.044
  servo_direction_inverted: true
  orientation:
    logo: "LEFT"
    usb: "UP"
  travel:
    min_angle: -32.3
    max_angle: 32.3
  aim_hysteresis: 2.0
  stall:
    timeout_sec: 0.25
    kick_power: 0.10
    progress_deg: 0.3
  pidf:
    p: 0.01424
    i: 0
    d: 0
    f: 0
  tolerance:
    max_drift: 3
    near_cutoff: 1
    near_val: 1.5
    min_deg: 0.5
    max_deg: 2
  analog_encoder:
    enabled: true
    zero_voltage: 2.5420
    degrees_per_volt: 42.15
    min_voltage: 0.079
    max_voltage: 1.705
    full_scale_voltage: 3.3
    inverted: true

vision:
  camera_position:
    x: -12
    y: 9
    z: 19.5
  camera_orientation:
    yaw: 0
    pitch: -90
    roll: 0

sentinel:
  robot_width: 18
  rotation_lookahead_time: 0.0685
  goals:
    size: 6
    min_y: 69
    red_goal_x: 128.5
    red_goal_y: 135
    blue_goal_x: 15.5
    blue_goal_y: 135

casablanca:
  enable_depth_protection: true
  enable_side_protection: true
  repulsion:
    power: 0.12
    decel_safety_factor: 0.7
  depth:
    slow_down: 15.0
    hard_stop: 10
  side:
    slow_down: 4
    hard_stop: 3
  lane_blend_distance: 12
  friction:
    x: 0.1041
    y: 0.1488
    rot: 0.1041
  smoothing:
    time: 0.22
    back_lift_multiplier: 2.5
  heading_lock:
    enabled: true
    intent_threshold: 0.05
    ks_moving: 0.0003
    moving_speed_threshold: 10.0
    max_power: 0.30
    error_deadband_deg: 2.0
    settle_rate_dps: 15.0


shooter:
  max_rpm: 1500
  min_transfer_threshold: 0.93
  max_velocity_threshold: 1.05
  feed_intake_power: 1.0
  feed_transfer_power: 1.0
  long_hood_power_threshold: 0.7
  hood:
    low_position: 0.156
    high_position: k+0.7
  pidf:
    p: 150
    i: 0
    d: 0
    f: 22.8
  launch_params:
    threshold_distance: 33
    near:
      launch_power: 0.4
      wait_time: 2000
    far:
      blue_base_power: 0.58
      red_base_power: 0.6
      power_scale: 300
      wait_time_scale: 68

auto:
  drink_wait_ms: 1200
  shoot_wait_ms: 1300
  launch_power: 0.71
  transfer_power: 0.12
  opposite_drink_wait_ms: 1250
  opposite_shoot_wait_ms: 2450
  opposite_launch_power: 0.86
  opposite_transfer_power: 0.12

teleop:
  max_speed: 1
  intake_power: 1.0
  transfer_power: 0.1
  manual_rev_power: 0.6
  poses:
    red:
      start: [87, 8, 91]
      score: [61, 21, 0]
      drink: [129, 60.5, 42]
      park: [37.5, 32, 270]
    blue:
      start: [57, 8, 90]
      score: [81, 21, 121]
      drink: [12, 60.5, 140]
      park: [105.5, 31, 270]

auto_poses:
  normal:
    blue:
      start: [27, 128, 135]
      score: [56, 80, 127]
      final_score: [57, 104, 144]
      drink_cp: [45, 72, 140]
      drink_end: [10.5, 61, 140]
      pickup1_cp: [41, 84, 180]
      pickup1_end: [18, 84, 180]
      pickup2_cp: [56, 55, 180]
      pickup2_end: [12, 59, 180]
      pickup3_cp: [56, 25, 180]
      pickup3_end: [11, 36, 180]
    red:
      start: m+1
      score: m
      final_score: m
      drink_cp: m
      drink_end: m
      pickup1_cp: m
      pickup1_end: m
      pickup2_cp: m
      pickup2_end: m
      pickup3_cp: m
      pickup3_end: m
  opposite:
    blue:
      start: [57, 8, 90]
      score: [59, 20, 111]
      drink_cp: [50, 50, 140]
      drink_end: [13, 60.5, 140]
      pickup2_cp: [60, 68, 180]
      pickup2_end: [12, 58, 180]
      pickup3_cp: [60, 40, 180]
      pickup3_end: [12, 36, 180]
      pickup4_cp: [50, 20, 190]
      pickup4_end: [12, 10, 190]
      park: [40, 20, 111]
    red:
      start: m
      score: m
      drink_cp: m
      drink_end: m
      pickup2_cp: m
      pickup2_end: m
      pickup3_cp: m
      pickup3_end: m
      pickup4_cp: m
      pickup4_end: m
      park: m
