# yaml-language-server: $schema=./config-schema.json
sentinel:
  robot_width: 18.0
  rotation_lookahead: 0.45
  goals:
    size: 6.0
    min_y: 69.0

casablanca:
  repulsion:
    power: 0.12
    decel_safety_factor: 0.7
  depth:
    slow_down: 8.0
    hard_stop: 10.0
  side:
    slow_down: 4.0
    hard_stop: 3.0
  lane_blend_distance: 12.0
