# yaml-language-server: $schema=./config-schema.json
caching:
  intake_tolerance: 0.01
  flywheel_tolerance: 0.005
  hood_tolerance: 0.002
  drivetrain_tolerance: 0.02

turret:
  max_turn_power: 0.5
  min_turn_power: 0.12
  max_power_output: 0.5
  feed_forward: 0.08
  orientation:
    logo: "RIGHT"
    usb: "UP"
  turn:
    offset_const: 260.0
    limit_const: 160.0
